# Usa una imagen base de .NET SDK para construir la aplicación
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copia el archivo .csproj y restaura las dependencias
COPY ../MiVeterinaria/*.csproj ./MiVeterinaria/
RUN dotnet restore ./MiVeterinaria/MiVeterinaria.csproj

# Copia el resto de los archivos del proyecto y compila
COPY ../MiVeterinaria/ ./MiVeterinaria/
RUN dotnet publish ./MiVeterinaria/MiVeterinaria.csproj -c Release -o out

# Usa una imagen base de .NET Runtime para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .

# Expone el puerto en el que la aplicación escuchará
EXPOSE 80

# Define el comando de entrada
ENTRYPOINT ["dotnet", "MiVeterinaria.dll"]